export default {
  "index": "🏠 홈",
  "curriculum": "🗺️ 전체 커리큘럼",
  "sep-intro": { "type": "separator", "title": "입문 (LEVEL 0~1)" },
  "01-overview": "01. 큰 그림",
  "02-kotlin-basics": "02. 코틀린 기초",
  "03-spring-boot": "03. 스프링 부트 입문",
  "04-securities-domain": "04. 증권 도메인 입문",
  "05-work-environment": "05. 실무 환경",
  "06-roadmap": "06. 30일 로드맵",
  "07-order-system-tutorial": "07. 실습: 주문 처리기",
  "08-architecture": "08. 아키텍처 개요",
  "16-dev-environment": "16. 개발 환경 구축",
  "17-jvm-fundamentals": "17. JVM 동작 원리",
  "sep-kotlin": { "type": "separator", "title": "코틀린 완전정복 (LEVEL 2)" },
  "18-kotlin-types-and-functions": "18. 타입 시스템과 함수",
  "19-kotlin-oop": "19. 객체지향과 설계",
  "20-kotlin-collections": "20. 컬렉션과 함수형",
  "21-kotlin-generics-and-idioms": "21. 제네릭과 관용구",
  "sep-eco": { "type": "separator", "title": "생태계 (LEVEL 3)" },
  "22-gradle-build": "22. Gradle 빌드",
  "23-testing": "23. 테스트 완전정복",
  "24-java-interop": "24. 자바 상호운용",
  "sep-spring": { "type": "separator", "title": "스프링 백엔드 (LEVEL 4)" },
  "25-spring-core": "25. 스프링 코어",
  "26-spring-boot-web": "26. 웹 계층 MVC/WebFlux",
  "27-data-access": "27. 데이터 접근",
  "14-rest-api": "14. REST API 실습",
  "sep-concurrency": { "type": "separator", "title": "동시성·비동기 (LEVEL 5)" },
  "11-concurrency": "11. 동시성과 잔고 정합성",
  "28-jvm-concurrency": "28. JVM 동시성 깊게",
  "13-coroutines": "13. 코루틴 입문",
  "29-coroutines-deep": "29. 코루틴 완전정복",
  "sep-domain": { "type": "separator", "title": "증권 도메인 (LEVEL 6)" },
  "30-market-structure": "30. 시장 구조와 매매제도",
  "31-order-types": "31. 주문 유형 전체",
  "32-clearing-settlement": "32. 청산·결제·정산",
  "33-account-ledger": "33. 계좌·원장·손익",
  "34-credit-derivatives": "34. 신용·파생 기초",
  "35-market-data": "35. 시세·시장 데이터",
  "36-risk-compliance": "36. 리스크·컴플라이언스",
  "sep-design": { "type": "separator", "title": "시스템 설계 초심화 (LEVEL 7)" },
  "10-bigdecimal-deep": "10. 금액 계산 완전정복",
  "12-orderbook": "12. 호가창 자료구조",
  "15-event-driven": "15. 이벤트 기반/Kafka",
  "37-low-latency": "37. 저지연 시스템 설계",
  "38-event-sourcing-cqrs": "38. 이벤트 소싱과 CQRS",
  "39-distributed-systems": "39. 분산 시스템과 일관성",
  "40-caching-redis": "40. 캐시 전략과 Redis",
  "41-high-availability": "41. 고가용성과 장애복구",
  "sep-ops": { "type": "separator", "title": "운영·보안 초심화 (LEVEL 8)" },
  "42-observability": "42. 관측성",
  "43-performance-tuning": "43. 성능 튜닝",
  "44-security": "44. 보안",
  "45-cicd-deploy": "45. CI/CD와 배포",
  "sep-dev-cs": { "type": "separator", "title": "개발자 CS 종합 (LEVEL 9)" },
  "58-cs-core": "58. CS 핵심 총정리",
  "59-networking-web-protocols": "59. 네트워크·웹 프로토콜",
  "60-backend-engineering": "60. 백엔드 엔지니어링",
  "61-frontend-engineering": "61. 프론트엔드 엔지니어링",
  "62-data-storage": "62. 데이터베이스·저장소",
  "63-linux-runtime": "63. 리눅스·런타임 운영",
  "64-infra-cloud": "64. 인프라·클라우드",
  "65-devops-sre": "65. DevOps·SRE",
  "66-security-engineering": "66. 보안 엔지니어링",
  "67-architecture-design": "67. 시스템 설계·아키텍처",
  "sep-capstone": { "type": "separator", "title": "캡스톤 (LEVEL 10)" },
  "46-capstone-project": "46. 미니 증권 시스템",
  "47-mastery-checklist": "47. 마스터 체크리스트",
  "sep-examples": { "type": "separator", "title": "예제" },
  "examples": "💻 예제 코드",
  "sep-glossary": { "type": "separator", "title": "용어집" },
  "09-glossary": "09. 용어집 완전판",
  "57-glossary-index": "57. 가나다순 색인",
  "50-glossary-backoffice": "50. 백오피스·정산·대사",
  "51-glossary-derivatives": "51. 파생상품 심화",
  "52-glossary-bonds": "52. 채권 심화",
  "53-glossary-funds": "53. 펀드·신탁·랩·구조화",
  "54-glossary-global": "54. 해외주식·외환",
  "55-glossary-marketdata": "55. 시세·체결시스템",
  "56-glossary-risk-compliance": "56. 리스크·컴플라이언스·규제"
}
